#! /usr/bin/env bash


ping -q -c 1 -W 1 8.8.8.8 >/dev/null 2>&1

if ! [ $? -eq 0 ] ; then
    printf "\n Not Connected Internet\a\n\n"
    exit 1
fi

b=$(  curl -s -u 'JL882262:$13derren' https://api.pinnacle.com/v1/client/balance ) 

balance=$( echo $b | jq '.availableBalance' )
standing=$( echo $b | jq '.outstandingTransactions' )

echo
printf "Balance  :\t%'.0f\n"  $balance
printf "Standing :\t%s\n" $standing
echo



#| sed 's/[{}"]//g;s/:/ /g' | awk -F, '{print "\n"$1"\n"$2"\n"$3"\n"$4 }' |  column -t
#{"availableBalance":0.0,"outstandingTransactions":0.0,"givenCredit":0.0,"currency":"KRW"}
